### ISSUE TITLE
TOKEN 

### ISSUE THREAD

**Issue by itrnltw** [adearman/memefi#2]
Token tidak valid semua meskipun udah diganti yang baru
padahal tadi siang masih bisa
![image](https://github.com/adearman/memefi/assets/152632108/513922af-8816-4843-a0a1-46b1ed2c675a)

**Comment by thanhnguyen92** [comment]
I have the same issue.

**Comment by boytegar** [comment]
ini ada perubahan dari memefi kayanya, response errornya bentukan html

**Comment by indexperience** [comment]
iya nih invalid token mulu padahal tokennya gak berubah

**Comment by itrnltw** [comment]
sertinya kena cloudflare
![image](https://github.com/adearman/memefi/assets/152632108/3959f749-53bb-4d86-8b17-d1ad38d92bcf)

**Comment by adearman** [comment]
join buat info update / tanya2
https://t.me/ghalibie

MEMEFI DAH UPDATE
